export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const DELETE_CART = "DELETE_CART";

export const GET_STORE_DETAILS = "GET_STORE_DETAILS";
